### ISSUE TITLE
Getting started (?)

### ISSUE THREAD

**Issue by lukasmedia** [lognoz/form-async#1]
I have cloned your repo, short question: where is form-async.js?

**Comment by lukasmedia** [comment]
Or; as described here:
https://www.jqueryscript.net/form/Auto-Send-Data-When-Form-Changes-jQuery-Quick-Autosave.html
autosave.min.js?

**Comment by lognoz** [comment]
Hi, I'm sorry about the delay.
You can find the `form-async.min.js` in `dist` directory. 

Have a good day :)
